{% set version = "2.22" %}
{% set sha256 = "acb149ee8cc4a582d9c56d5fb0bba8b0de628d56f8527dde2e3285006a58480b" %}
{% set tag = version %}

package:
  name: coda
  version: {{ version }} 

source:
  url: https://github.com/stcorp/coda/releases/download/{{ tag }}/coda-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 2

requirements:
  build:
    - cmake
    - bison  # [not win]
    - flex  # [not win]
    - m2-bison  # [win]
    - m2-flex  # [win]
    - python
    - numpy
    - zlib
    - hdf4
    - hdf5 <1.12
    - jpeg

  run:
    - vs2015_runtime  # [win]
    - python
    - numpy
    - zlib
    - hdf4
    - hdf5
    - jpeg

about:
  home: https://github.com/stcorp/coda
  license: BSD
  license_file: COPYING

